export interface Session {
  id: string;
  name: string;
  createdAt: string;
}

export interface Column {
  id: number; // auto-generated by db
  sessionId: string;
  name: string; // display name: "What Went Well", "Needs Improvement"
  position: number;
  color: string;
  createdAt: string;
}
export type ColumnType = 'went_well' | 'improve' | 'actions';

export interface Card {
  id: number; // auto-generated by db
  sessionId: string;
  columnId: number; // references columns.id
  content: string;
  position: number;
  createdAt: string;
  createdBy?: string;
}

export interface ActionItem {
  id: number; // auto-generated by db
  sessionId: string;
  title: string;
  description?: string;
  assignedTo?: string;
  status: 'pending' | 'in_progress' | 'completed';
  createdAt: string;
}


// request types
export interface CreateSessionRequest {
  name?: string;
}

export interface CreateCardRequest {
  sessionId: string;
  content: string;
  columnId: number;
  position: number;
}

export interface UpdateCardRequest {
  content?: string;
  columnId?: number;
  position?: number;
}

export interface CreateColumnRequest {
    sessionId: string;
    name: string;
    position: number;
    color: string;
  }

  export interface CreateActionItemRequest {
    sessionId: string;
    title: string;
    description?: string;
    assignedTo?: string;
  }

  export interface UpdateActionItemRequest {
    title?: string;
    description?: string;
    assignedTo?: string;
    status?: 'pending' | 'in_progress' | 'completed';
  }
